ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: &host podinfo.k8sj.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - *host
      secretName: podinfo-tls
