---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: linkerd-crds
    repo: https://helm.linkerd.io/edge
    version: "2025.1.1"
    releaseName: linkerd-crd
    includeCRDs: true
    namespace: kube-system
