deployment:
  podAnnotations:
    linkerd.io/inject: ingress
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-linkerd
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
logs:
  access:
    enabled: true
ports:
  traefik:
    expose: true
ingressRoute:
  dashboard:
    enabled: true
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    entryPoints: ["web"]
